# This is a basic workflow to help you get started with Actions

name: Trigger with merge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  merge_group:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  zero:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir teste
          cd teste
          echo "banana" > banana.txt
          cat banana.txt
        
      - uses: actions/cache@v4
        with:
          path: teste
          key: teste

  two:
    needs: one
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "success"

  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -la

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
          git rev-parse HEAD^1
          git rev-parse HEAD
          echo "NEW_NX_BASE=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "NEW_BASE: ${{ env.NEW_NX_BASE }}"
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
          echo Add other actions to build,
          sleep 30

      
