# This is a basic workflow to help you get started with Actions

name: Trigger with PR

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write # Permite ler e escrever conteúdo no repositório
  issues: write    # Permite adicionar e modificar comentários em issues e PRs
  pull-requests: write  # Permite adicionar comentários em pull requests

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  banana:
    runs-on: ubuntu-latest
    steps:
      - name: Announcement Pull Request
        uses: paulo9mv/announcement_pull_request@v0.4.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Oi galera"
            
  zero:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true

  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sucesso"

  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sucesso"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: zero

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sleep 5

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
