# This is a basic workflow to help you get started with Actions

name: Trigger with PR

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
      - synchronize

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  zero:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache/restore@v4
        env:
          cache-name: cache-node-modules
        with:
          path: teste
          key: ${{ runner.os }}-build-${{ env.cache-name }}paulo
          lookup-only: true

      - name: Display results
        run: |
          - echo ${{ steps.cache-node-modules.outputs.cache-hit }}

      - name: Display results 1
        if: steps.cache-node-modules.outputs.cache-hit == 'false'
        run: |
          - echo ${{ steps.cache-node-modules.outputs.cache-hit }}

      - name: Display results 2
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: |
          - echo ${{ steps.cache-node-modules.outputs.cache-hit }}

      - name: Display results 3
        if: steps.cache-node-modules.outputs.cache-hit == true
        run: |
          - echo ${{ steps.cache-node-modules.outputs.cache-hit }}

      - name: Display results 4
        if: steps.cache-node-modules.outputs.cache-hit == false
        run: |
          - echo ${{ steps.cache-node-modules.outputs.cache-hit }}
  

  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sucesso"

  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sucesso"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: zero

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sleep 5

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
