# This is a basic workflow to help you get started with Actions

name: Trigger with PR

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
      - synchronize

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  zero:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true

  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sucesso"

  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sucesso"

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: zero

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sleep 15

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  teste:
    runs-on: ubuntu-latest
    name: Run n${{ matrix.index }}
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive reports artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.index }}
          path: macro/**/arquivo-${{ matrix.index }}-*.html
          if-no-files-found: ignore

  check-test:
    runs-on: ubuntu-latest
    needs: teste
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download reports artifacts
        uses: actions/download-artifact@v4
        with:
          path: macro
          pattern: reports-*
          merge-multiple: true

      - name: List reports
        run: ls -R .
        continue-on-error: true

      - name: Run a one-line script
        run: echo "Sucesso"
