name: "test-on-comment"

on:
  issue_comment:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Choose the application to deploy to PROD environment
        options:
          - sao
        required: true
      version:
        type: string
        description: Confirm the tag that will be deployed to PROD environment
        required: true

env:
  GH_TOKEN_BANK_ADMIN: ${{ secrets.GH_TOKEN_BANK_ADMIN }}
  FORCE_COLOR: true

permissions: write-all

jobs:
  check-tests:
    name: Check comment ${{ github.ref_name }}
    if: ${{ (github.event.issue.pull_request && github.event.comment.body == '/run-tests') }}
    runs-on: ubuntu-latest
    steps:
      - name: Cache event
        uses: actions/cache@v4
        with:
          path: teste
          key: ${{ runner.os }}-${{ github.event.comment.id }}

      - run: mkdir teste
      - run: |
          echo "paulo" >> teste/testefile
          ls
