name: "test-on-comment"

on:
  issue_comment:

concurrency:
  group: ${{ github.ref }}-${{ github.event.issue.number }}-${{ contains(github.event.comment.body, '/run-tests') }}-comment
  cancel-in-progress: true

env:
  GH_TOKEN_BANK_ADMIN: ${{ secrets.GH_TOKEN_BANK_ADMIN }}
  FORCE_COLOR: true

jobs:
  check-tests:
    name: Check comment
    if: ${{ (github.event.issue.pull_request && github.event.comment.body == '/run-tests') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
