name: "test-on-comment"

on:
  issue_comment:

concurrency:
  group: ${{ github.ref }}-${{ github.event.issue.number }}-${{ contains(github.event.comment.body, '/run-tests') }}-comment
  cancel-in-progress: true

env:
  GH_TOKEN_BANK_ADMIN: ${{ secrets.GH_TOKEN_BANK_ADMIN }}
  FORCE_COLOR: true

permissions: write-all

jobs:
  check-tests:
    name: Check comment
    if: ${{ (github.event.issue.pull_request && github.event.comment.body == '/run-tests') }}
    runs-on: ubuntu-latest
    steps:
      - name: Cache event
        uses: actions/cache@v4
        with:
          path: teste
          key: ${{ runner.os }}-${{ github.event.comment.id }}

      - run: mkdir teste
      - run: |
          echo "paulo" >> teste/testefile
          ls
